name: flakka_buf_runner
description: A run-process helper for using the buf CLI
version: 0.2.0-alpha.1
repository: https://github.com/flakka-code/flakka_buf_runner
environment:
  sdk: "^3.3.0"

dependencies:
  build: ^2.4.1
  glob: ^2.1.2
  path: ^1.9.0
  scratch_space: ^1.0.2

dev_dependencies:
  build_test: ^2.2.2
  test: ^1.25.2
  very_good_analysis: ^5.1.0
