name: flakka_buf_runner
description: A run-process helper for using the buf CLI
version: 0.2.0-alpha.1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  glob:
  path:
  scratch_space:

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^5.1.0
